apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-autoscaler
  namespace: kube-system
  annotations:
    # ARN del rol de IAM para el Service Account
    eks.amazonaws.com/role-arn: arn:aws:iam::162523333259:role/eks-cluster-autoscaler
