apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx-pod-principal
  name: nginx-pod-principal
spec:
  nodeSelector:
    type: on-demand
  containers:
  - image: nginx
    name: nginx-pod-principal
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
